apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secrets
type: Opaque
data:
  TELEGRAM_TOKEN: NzQ4MTkwNjUwMTpBQUV6UmxONHVpNmhmbkhQMmFBM1hicVhWYWt0MUFOM3ZMSQ==
  WEATHER_API_KEY: MDcwMjliMTNiZDNkYTcwY2MyYmZhMTllZDMwMmIxNTk=
